package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Depart generated by hbm2java
 */
public class Depart implements java.io.Serializable {

	private int departId;
	private String departName;
	private String departInfo;
	private Integer departRank;
	private Set employeesForDepartId = new HashSet(0);
	private Set employeesForDepDepartId = new HashSet(0);

	public Depart() {
	}

	public Depart(int departId, String departName) {
		this.departId = departId;
		this.departName = departName;
	}

	public Depart(int departId, String departName, String departInfo, Integer departRank, Set employeesForDepartId,
			Set employeesForDepDepartId) {
		this.departId = departId;
		this.departName = departName;
		this.departInfo = departInfo;
		this.departRank = departRank;
		this.employeesForDepartId = employeesForDepartId;
		this.employeesForDepDepartId = employeesForDepDepartId;
	}

	public int getDepartId() {
		return this.departId;
	}

	public void setDepartId(int departId) {
		this.departId = departId;
	}

	public String getDepartName() {
		return this.departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	public String getDepartInfo() {
		return this.departInfo;
	}

	public void setDepartInfo(String departInfo) {
		this.departInfo = departInfo;
	}

	public Integer getDepartRank() {
		return this.departRank;
	}

	public void setDepartRank(Integer departRank) {
		this.departRank = departRank;
	}

	public Set getEmployeesForDepartId() {
		return this.employeesForDepartId;
	}

	public void setEmployeesForDepartId(Set employeesForDepartId) {
		this.employeesForDepartId = employeesForDepartId;
	}

	public Set getEmployeesForDepDepartId() {
		return this.employeesForDepDepartId;
	}

	public void setEmployeesForDepDepartId(Set employeesForDepDepartId) {
		this.employeesForDepDepartId = employeesForDepDepartId;
	}

}
