package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int employeeId;
	private Depart departByDepartId;
	private Depart departByDepDepartId;
	private Task task;
	private String employeeName;
	private Boolean employeeSex;
	private String employeePhone;
	private int employeePosition;
	private Set leavewords = new HashSet(0);
	private Set performances = new HashSet(0);
	private Set houses = new HashSet(0);
	private Set followups = new HashSet(0);
	private Set workrecords = new HashSet(0);
	private Set logs = new HashSet(0);
	private Set keycontrolls = new HashSet(0);
	private Set tasks = new HashSet(0);

	public Employee() {
	}

	public Employee(int employeeId, String employeeName, int employeePosition) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeePosition = employeePosition;
	}

	public Employee(int employeeId, Depart departByDepartId, Depart departByDepDepartId, Task task, String employeeName,
			Boolean employeeSex, String employeePhone, int employeePosition, Set leavewords, Set performances,
			Set houses, Set followups, Set workrecords, Set logs, Set keycontrolls, Set tasks) {
		this.employeeId = employeeId;
		this.departByDepartId = departByDepartId;
		this.departByDepDepartId = departByDepDepartId;
		this.task = task;
		this.employeeName = employeeName;
		this.employeeSex = employeeSex;
		this.employeePhone = employeePhone;
		this.employeePosition = employeePosition;
		this.leavewords = leavewords;
		this.performances = performances;
		this.houses = houses;
		this.followups = followups;
		this.workrecords = workrecords;
		this.logs = logs;
		this.keycontrolls = keycontrolls;
		this.tasks = tasks;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Depart getDepartByDepartId() {
		return this.departByDepartId;
	}

	public void setDepartByDepartId(Depart departByDepartId) {
		this.departByDepartId = departByDepartId;
	}

	public Depart getDepartByDepDepartId() {
		return this.departByDepDepartId;
	}

	public void setDepartByDepDepartId(Depart departByDepDepartId) {
		this.departByDepDepartId = departByDepDepartId;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Boolean getEmployeeSex() {
		return this.employeeSex;
	}

	public void setEmployeeSex(Boolean employeeSex) {
		this.employeeSex = employeeSex;
	}

	public String getEmployeePhone() {
		return this.employeePhone;
	}

	public void setEmployeePhone(String employeePhone) {
		this.employeePhone = employeePhone;
	}

	public int getEmployeePosition() {
		return this.employeePosition;
	}

	public void setEmployeePosition(int employeePosition) {
		this.employeePosition = employeePosition;
	}

	public Set getLeavewords() {
		return this.leavewords;
	}

	public void setLeavewords(Set leavewords) {
		this.leavewords = leavewords;
	}

	public Set getPerformances() {
		return this.performances;
	}

	public void setPerformances(Set performances) {
		this.performances = performances;
	}

	public Set getHouses() {
		return this.houses;
	}

	public void setHouses(Set houses) {
		this.houses = houses;
	}

	public Set getFollowups() {
		return this.followups;
	}

	public void setFollowups(Set followups) {
		this.followups = followups;
	}

	public Set getWorkrecords() {
		return this.workrecords;
	}

	public void setWorkrecords(Set workrecords) {
		this.workrecords = workrecords;
	}

	public Set getLogs() {
		return this.logs;
	}

	public void setLogs(Set logs) {
		this.logs = logs;
	}

	public Set getKeycontrolls() {
		return this.keycontrolls;
	}

	public void setKeycontrolls(Set keycontrolls) {
		this.keycontrolls = keycontrolls;
	}

	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

}
