package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Followup generated by hbm2java
 */
public class Followup implements java.io.Serializable {

	private int followUpId;
	private Custom custom;
	private Employee employee;
	private House house;
	private int followUpStatue;
	private Date followUpDate;

	public Followup() {
	}

	public Followup(int followUpId, Custom custom, Employee employee, House house, int followUpStatue,
			Date followUpDate) {
		this.followUpId = followUpId;
		this.custom = custom;
		this.employee = employee;
		this.house = house;
		this.followUpStatue = followUpStatue;
		this.followUpDate = followUpDate;
	}

	public int getFollowUpId() {
		return this.followUpId;
	}

	public void setFollowUpId(int followUpId) {
		this.followUpId = followUpId;
	}

	public Custom getCustom() {
		return this.custom;
	}

	public void setCustom(Custom custom) {
		this.custom = custom;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public int getFollowUpStatue() {
		return this.followUpStatue;
	}

	public void setFollowUpStatue(int followUpStatue) {
		this.followUpStatue = followUpStatue;
	}

	public Date getFollowUpDate() {
		return this.followUpDate;
	}

	public void setFollowUpDate(Date followUpDate) {
		this.followUpDate = followUpDate;
	}

}
