package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Housemap generated by hbm2java
 */
public class Housemap implements java.io.Serializable {

	private int houseMapId;
	private House house;
	private String position;
	private String image;
	private Date updateTime;

	public Housemap() {
	}

	public Housemap(int houseMapId, House house, String position, Date updateTime) {
		this.houseMapId = houseMapId;
		this.house = house;
		this.position = position;
		this.updateTime = updateTime;
	}

	public Housemap(int houseMapId, House house, String position, String image, Date updateTime) {
		this.houseMapId = houseMapId;
		this.house = house;
		this.position = position;
		this.image = image;
		this.updateTime = updateTime;
	}

	public int getHouseMapId() {
		return this.houseMapId;
	}

	public void setHouseMapId(int houseMapId) {
		this.houseMapId = houseMapId;
	}

	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
