package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * House generated by hbm2java
 */
public class House implements java.io.Serializable {

	private int houseId;
	private Employee employee;
	private Housekey housekey;
	private boolean rentStatue;
	private boolean saleStatue;
	private float houseArea;
	private Float unitRentPrice;
	private Float unitSalePrice;
	private String clientName;
	private String clientPhone;
	private Set pacts = new HashSet(0);
	private Set followups = new HashSet(0);
	private Set housemaps = new HashSet(0);

	public House() {
	}

	public House(int houseId, Housekey housekey, boolean rentStatue, boolean saleStatue, float houseArea,
			String clientName) {
		this.houseId = houseId;
		this.housekey = housekey;
		this.rentStatue = rentStatue;
		this.saleStatue = saleStatue;
		this.houseArea = houseArea;
		this.clientName = clientName;
	}

	public House(int houseId, Employee employee, Housekey housekey, boolean rentStatue, boolean saleStatue,
			float houseArea, Float unitRentPrice, Float unitSalePrice, String clientName, String clientPhone, Set pacts,
			Set followups, Set housemaps) {
		this.houseId = houseId;
		this.employee = employee;
		this.housekey = housekey;
		this.rentStatue = rentStatue;
		this.saleStatue = saleStatue;
		this.houseArea = houseArea;
		this.unitRentPrice = unitRentPrice;
		this.unitSalePrice = unitSalePrice;
		this.clientName = clientName;
		this.clientPhone = clientPhone;
		this.pacts = pacts;
		this.followups = followups;
		this.housemaps = housemaps;
	}

	public int getHouseId() {
		return this.houseId;
	}

	public void setHouseId(int houseId) {
		this.houseId = houseId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Housekey getHousekey() {
		return this.housekey;
	}

	public void setHousekey(Housekey housekey) {
		this.housekey = housekey;
	}

	public boolean isRentStatue() {
		return this.rentStatue;
	}

	public void setRentStatue(boolean rentStatue) {
		this.rentStatue = rentStatue;
	}

	public boolean isSaleStatue() {
		return this.saleStatue;
	}

	public void setSaleStatue(boolean saleStatue) {
		this.saleStatue = saleStatue;
	}

	public float getHouseArea() {
		return this.houseArea;
	}

	public void setHouseArea(float houseArea) {
		this.houseArea = houseArea;
	}

	public Float getUnitRentPrice() {
		return this.unitRentPrice;
	}

	public void setUnitRentPrice(Float unitRentPrice) {
		this.unitRentPrice = unitRentPrice;
	}

	public Float getUnitSalePrice() {
		return this.unitSalePrice;
	}

	public void setUnitSalePrice(Float unitSalePrice) {
		this.unitSalePrice = unitSalePrice;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientPhone() {
		return this.clientPhone;
	}

	public void setClientPhone(String clientPhone) {
		this.clientPhone = clientPhone;
	}

	public Set getPacts() {
		return this.pacts;
	}

	public void setPacts(Set pacts) {
		this.pacts = pacts;
	}

	public Set getFollowups() {
		return this.followups;
	}

	public void setFollowups(Set followups) {
		this.followups = followups;
	}

	public Set getHousemaps() {
		return this.housemaps;
	}

	public void setHousemaps(Set housemaps) {
		this.housemaps = housemaps;
	}

}
