package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Housekey generated by hbm2java
 */
public class Housekey implements java.io.Serializable {

	private int houseKey;
	private boolean houseKeyStatue;
	private Set keycontrolls = new HashSet(0);
	private Set houses = new HashSet(0);

	public Housekey() {
	}

	public Housekey(int houseKey, boolean houseKeyStatue) {
		this.houseKey = houseKey;
		this.houseKeyStatue = houseKeyStatue;
	}

	public Housekey(int houseKey, boolean houseKeyStatue, Set keycontrolls, Set houses) {
		this.houseKey = houseKey;
		this.houseKeyStatue = houseKeyStatue;
		this.keycontrolls = keycontrolls;
		this.houses = houses;
	}

	public int getHouseKey() {
		return this.houseKey;
	}

	public void setHouseKey(int houseKey) {
		this.houseKey = houseKey;
	}

	public boolean isHouseKeyStatue() {
		return this.houseKeyStatue;
	}

	public void setHouseKeyStatue(boolean houseKeyStatue) {
		this.houseKeyStatue = houseKeyStatue;
	}

	public Set getKeycontrolls() {
		return this.keycontrolls;
	}

	public void setKeycontrolls(Set keycontrolls) {
		this.keycontrolls = keycontrolls;
	}

	public Set getHouses() {
		return this.houses;
	}

	public void setHouses(Set houses) {
		this.houses = houses;
	}

}
