package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Keycontroll generated by hbm2java
 */
public class Keycontroll implements java.io.Serializable {

	private int keyControllId;
	private Employee employee;
	private Housekey housekey;
	private boolean isApprove;
	private Date approveDate;
	private Date planReturnDate;
	private Date actualReturnDate;

	public Keycontroll() {
	}

	public Keycontroll(int keyControllId, Employee employee, Housekey housekey, boolean isApprove, Date approveDate) {
		this.keyControllId = keyControllId;
		this.employee = employee;
		this.housekey = housekey;
		this.isApprove = isApprove;
		this.approveDate = approveDate;
	}

	public Keycontroll(int keyControllId, Employee employee, Housekey housekey, boolean isApprove, Date approveDate,
			Date planReturnDate, Date actualReturnDate) {
		this.keyControllId = keyControllId;
		this.employee = employee;
		this.housekey = housekey;
		this.isApprove = isApprove;
		this.approveDate = approveDate;
		this.planReturnDate = planReturnDate;
		this.actualReturnDate = actualReturnDate;
	}

	public int getKeyControllId() {
		return this.keyControllId;
	}

	public void setKeyControllId(int keyControllId) {
		this.keyControllId = keyControllId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Housekey getHousekey() {
		return this.housekey;
	}

	public void setHousekey(Housekey housekey) {
		this.housekey = housekey;
	}

	public boolean isIsApprove() {
		return this.isApprove;
	}

	public void setIsApprove(boolean isApprove) {
		this.isApprove = isApprove;
	}

	public Date getApproveDate() {
		return this.approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	public Date getPlanReturnDate() {
		return this.planReturnDate;
	}

	public void setPlanReturnDate(Date planReturnDate) {
		this.planReturnDate = planReturnDate;
	}

	public Date getActualReturnDate() {
		return this.actualReturnDate;
	}

	public void setActualReturnDate(Date actualReturnDate) {
		this.actualReturnDate = actualReturnDate;
	}

}
