package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Leaveword generated by hbm2java
 */
public class Leaveword implements java.io.Serializable {

	private int leaveWordId;
	private Employee employee;
	private Leaveword leaveword;
	private String leaveWordContent;
	private Date leaveWordDate;
	private Boolean anonymousStatue;
	private Set leavewords = new HashSet(0);

	public Leaveword() {
	}

	public Leaveword(int leaveWordId, Employee employee, String leaveWordContent, Date leaveWordDate) {
		this.leaveWordId = leaveWordId;
		this.employee = employee;
		this.leaveWordContent = leaveWordContent;
		this.leaveWordDate = leaveWordDate;
	}

	public Leaveword(int leaveWordId, Employee employee, Leaveword leaveword, String leaveWordContent,
			Date leaveWordDate, Boolean anonymousStatue, Set leavewords) {
		this.leaveWordId = leaveWordId;
		this.employee = employee;
		this.leaveword = leaveword;
		this.leaveWordContent = leaveWordContent;
		this.leaveWordDate = leaveWordDate;
		this.anonymousStatue = anonymousStatue;
		this.leavewords = leavewords;
	}

	public int getLeaveWordId() {
		return this.leaveWordId;
	}

	public void setLeaveWordId(int leaveWordId) {
		this.leaveWordId = leaveWordId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Leaveword getLeaveword() {
		return this.leaveword;
	}

	public void setLeaveword(Leaveword leaveword) {
		this.leaveword = leaveword;
	}

	public String getLeaveWordContent() {
		return this.leaveWordContent;
	}

	public void setLeaveWordContent(String leaveWordContent) {
		this.leaveWordContent = leaveWordContent;
	}

	public Date getLeaveWordDate() {
		return this.leaveWordDate;
	}

	public void setLeaveWordDate(Date leaveWordDate) {
		this.leaveWordDate = leaveWordDate;
	}

	public Boolean getAnonymousStatue() {
		return this.anonymousStatue;
	}

	public void setAnonymousStatue(Boolean anonymousStatue) {
		this.anonymousStatue = anonymousStatue;
	}

	public Set getLeavewords() {
		return this.leavewords;
	}

	public void setLeavewords(Set leavewords) {
		this.leavewords = leavewords;
	}

}
