package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private int logId;
	private Employee employee;
	private Date logDate;
	private Date quitDate;

	public Log() {
	}

	public Log(int logId, Date logDate) {
		this.logId = logId;
		this.logDate = logDate;
	}

	public Log(int logId, Employee employee, Date logDate, Date quitDate) {
		this.logId = logId;
		this.employee = employee;
		this.logDate = logDate;
		this.quitDate = quitDate;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	public Date getQuitDate() {
		return this.quitDate;
	}

	public void setQuitDate(Date quitDate) {
		this.quitDate = quitDate;
	}

}
