package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pact generated by hbm2java
 */
public class Pact implements java.io.Serializable {

	private int pactId;
	private House house;
	private Performance performance;
	private int pactStatue;
	private Date pactDate;
	private String pactInfo;
	private Set performances = new HashSet(0);

	public Pact() {
	}

	public Pact(int pactId, House house, int pactStatue, Date pactDate) {
		this.pactId = pactId;
		this.house = house;
		this.pactStatue = pactStatue;
		this.pactDate = pactDate;
	}

	public Pact(int pactId, House house, Performance performance, int pactStatue, Date pactDate, String pactInfo,
			Set performances) {
		this.pactId = pactId;
		this.house = house;
		this.performance = performance;
		this.pactStatue = pactStatue;
		this.pactDate = pactDate;
		this.pactInfo = pactInfo;
		this.performances = performances;
	}

	public int getPactId() {
		return this.pactId;
	}

	public void setPactId(int pactId) {
		this.pactId = pactId;
	}

	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public Performance getPerformance() {
		return this.performance;
	}

	public void setPerformance(Performance performance) {
		this.performance = performance;
	}

	public int getPactStatue() {
		return this.pactStatue;
	}

	public void setPactStatue(int pactStatue) {
		this.pactStatue = pactStatue;
	}

	public Date getPactDate() {
		return this.pactDate;
	}

	public void setPactDate(Date pactDate) {
		this.pactDate = pactDate;
	}

	public String getPactInfo() {
		return this.pactInfo;
	}

	public void setPactInfo(String pactInfo) {
		this.pactInfo = pactInfo;
	}

	public Set getPerformances() {
		return this.performances;
	}

	public void setPerformances(Set performances) {
		this.performances = performances;
	}

}
