package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Performance generated by hbm2java
 */
public class Performance implements java.io.Serializable {

	private int performanceId;
	private Custom custom;
	private Employee employee;
	private Pact pact;
	private int employeeCoustomState;
	private int customType;
	private Date registerDate;
	private Date completeDate;
	private String performanceInfo;
	private Set pacts = new HashSet(0);

	public Performance() {
	}

	public Performance(int performanceId, Employee employee, int employeeCoustomState, int customType,
			Date registerDate) {
		this.performanceId = performanceId;
		this.employee = employee;
		this.employeeCoustomState = employeeCoustomState;
		this.customType = customType;
		this.registerDate = registerDate;
	}

	public Performance(int performanceId, Custom custom, Employee employee, Pact pact, int employeeCoustomState,
			int customType, Date registerDate, Date completeDate, String performanceInfo, Set pacts) {
		this.performanceId = performanceId;
		this.custom = custom;
		this.employee = employee;
		this.pact = pact;
		this.employeeCoustomState = employeeCoustomState;
		this.customType = customType;
		this.registerDate = registerDate;
		this.completeDate = completeDate;
		this.performanceInfo = performanceInfo;
		this.pacts = pacts;
	}

	public int getPerformanceId() {
		return this.performanceId;
	}

	public void setPerformanceId(int performanceId) {
		this.performanceId = performanceId;
	}

	public Custom getCustom() {
		return this.custom;
	}

	public void setCustom(Custom custom) {
		this.custom = custom;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Pact getPact() {
		return this.pact;
	}

	public void setPact(Pact pact) {
		this.pact = pact;
	}

	public int getEmployeeCoustomState() {
		return this.employeeCoustomState;
	}

	public void setEmployeeCoustomState(int employeeCoustomState) {
		this.employeeCoustomState = employeeCoustomState;
	}

	public int getCustomType() {
		return this.customType;
	}

	public void setCustomType(int customType) {
		this.customType = customType;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Date getCompleteDate() {
		return this.completeDate;
	}

	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	public String getPerformanceInfo() {
		return this.performanceInfo;
	}

	public void setPerformanceInfo(String performanceInfo) {
		this.performanceInfo = performanceInfo;
	}

	public Set getPacts() {
		return this.pacts;
	}

	public void setPacts(Set pacts) {
		this.pacts = pacts;
	}

}
