package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private int taskId;
	private Employee employee;
	private Date planDo;
	private Date publishDate;
	private boolean taskStatue;
	private Integer taskLevel;
	private String taskInfo;
	private Set employees = new HashSet(0);

	public Task() {
	}

	public Task(int taskId, Employee employee, Date planDo, Date publishDate, boolean taskStatue) {
		this.taskId = taskId;
		this.employee = employee;
		this.planDo = planDo;
		this.publishDate = publishDate;
		this.taskStatue = taskStatue;
	}

	public Task(int taskId, Employee employee, Date planDo, Date publishDate, boolean taskStatue, Integer taskLevel,
			String taskInfo, Set employees) {
		this.taskId = taskId;
		this.employee = employee;
		this.planDo = planDo;
		this.publishDate = publishDate;
		this.taskStatue = taskStatue;
		this.taskLevel = taskLevel;
		this.taskInfo = taskInfo;
		this.employees = employees;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getPlanDo() {
		return this.planDo;
	}

	public void setPlanDo(Date planDo) {
		this.planDo = planDo;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public boolean isTaskStatue() {
		return this.taskStatue;
	}

	public void setTaskStatue(boolean taskStatue) {
		this.taskStatue = taskStatue;
	}

	public Integer getTaskLevel() {
		return this.taskLevel;
	}

	public void setTaskLevel(Integer taskLevel) {
		this.taskLevel = taskLevel;
	}

	public String getTaskInfo() {
		return this.taskInfo;
	}

	public void setTaskInfo(String taskInfo) {
		this.taskInfo = taskInfo;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
