package hibernate;
// Generated 2017-3-18 21:28:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Workrecord generated by hbm2java
 */
public class Workrecord implements java.io.Serializable {

	private int workRecordId;
	private Employee employee;
	private Date workRecordDate;
	private Date actualSignIn;
	private Date leaveSignIn;

	public Workrecord() {
	}

	public Workrecord(int workRecordId, Employee employee, Date workRecordDate) {
		this.workRecordId = workRecordId;
		this.employee = employee;
		this.workRecordDate = workRecordDate;
	}

	public Workrecord(int workRecordId, Employee employee, Date workRecordDate, Date actualSignIn, Date leaveSignIn) {
		this.workRecordId = workRecordId;
		this.employee = employee;
		this.workRecordDate = workRecordDate;
		this.actualSignIn = actualSignIn;
		this.leaveSignIn = leaveSignIn;
	}

	public int getWorkRecordId() {
		return this.workRecordId;
	}

	public void setWorkRecordId(int workRecordId) {
		this.workRecordId = workRecordId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getWorkRecordDate() {
		return this.workRecordDate;
	}

	public void setWorkRecordDate(Date workRecordDate) {
		this.workRecordDate = workRecordDate;
	}

	public Date getActualSignIn() {
		return this.actualSignIn;
	}

	public void setActualSignIn(Date actualSignIn) {
		this.actualSignIn = actualSignIn;
	}

	public Date getLeaveSignIn() {
		return this.leaveSignIn;
	}

	public void setLeaveSignIn(Date leaveSignIn) {
		this.leaveSignIn = leaveSignIn;
	}

}
